---
title: "BACandSTRAW VOC PCoA Visuals"
author: "Brown, J.T."
date: "MAy 22, 2019"
output: html_document
---

### ##General Background## 
### ##Speciic Background##
### ##Problem/Gap##
### ##describe Analysis##
### ##Implications##

```{r setup, include=FALSE}
# Libraries and Data Frames
##what you need to install phyloseq
#source('http://bioconductor.org/biocLite.R')
#biocLite('phyloseq')
#install.packages("devtools")
#install_github("vqv/ggbiplot")
#install.packages("gdata")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
#BiocManager::install()
library(gdata)
library(devtools)
library(ggplot2)
library(beeswarm)
library(phyloseq) #install via bioconductor
library(vegan)
library(ggbiplot)
library(readxl)
library(readr)
library(ape)
library("DESeq2")
```

```{r}
# read in data
meta <- read.csv("/Users/jbrown/Documents/GitHub/BACandBlue/data/BACandSTRAW_SUBSET_SWDvsSBERRY_BLANK_PRO_REP/meta.csv") 
meta$hour=as.factor(meta$hour)
rownames(meta) <- meta$SampleID_merge 
SAMP <- sample_data(meta)
sample_names(SAMP)<-meta$SampleID

peaks <- read.csv("/Users/jbrown/Documents/GitHub/BACandBlue/data/BACandSTRAW_SUBSET_SWDvsSBERRY_BLANK_PRO_REP/peak.csv")
TAX <- tax_table(peaks) # gives a warning, don't freak out
taxa_names(TAX)<-peaks$Peak_ID
colnames(TAX)<- colnames(peaks)

abund <- read.csv("/Users/jbrown/Documents/GitHub/BACandBlue/data/BACandSTRAW_SUBSET_SWDvsSBERRY_BLANK_PRO_REP/otu.csv", colClasses = c("factor","factor", rep("numeric", times= 14)))
# read in peak areas, assigning factors of diff classifications based on columns
rownames(abund) <- abund$Peak_ID #give abund rows names according to "Peak_ID" in peak.csv table
OTU <- otu_table(abund[,-c(1:2)], taxa_are_rows=T) #create a table with only peak areas, compounds are taxa


VOC <- phyloseq(OTU, TAX, SAMP) #IF YOU GET A "SAMPLE_NAMES()" ERROR MAKE SURE YOUR NAMES DO NOT START WITH A NUMBER

#returns: "phyloseq-class experiment-level object
#otu_table()   OTU Table:       [ 77 taxa and 14 samples ] "taxa" = VOCs "samples" = SPME-HS samples
#sample_data() Sample Data:     [ 14 samples by 9 sample variables ] "sample variable" = categories
#tax_table()   Taxonomy Table:  [ 77 taxa by 2 taxonomic ranks ] "taxonomic rank" = sample time/hour"

```


```{r}
##############
#    PCoAs   #
##############


###	#PCoA with Bray-Curtis Distances#	###
ord <- ordinate(VOC, method = "PCoA", distance = "bray")
plot_ordination(VOC, ord, color = "hour", shape = "microbe", label = "rep")+
  theme_bw() + theme(text = element_text(size = 20)) + geom_point(size = 4)
plot_ordination(VOC, ord, type = "juice", color = "hour", shape = "microbe", label = "rep")+
  theme_bw() + theme(text = element_text(size = 20)) + geom_point(size = 4)

PCs <- data.frame(scores(ord$vectors))
new.dat <- cbind(PCs, sample_data(VOC)$microbe, sample_data(VOC)$rep, sample_data(VOC)$hour) # make a new matrix
names(new.dat)[12:14] <- c("Microbe","Rep","Hour") #for the "must be the same length as vector" error make sure that the info inside the bracets matches empty columns in the dataframe your creating"
library(gdata)
new.dat$Microbe <- reorder.factor(new.dat$Microbe, new.order = c("SWD"))
new.dat$Hour <- reorder.factor(new.dat$Hour, new.order = c("24","48"))

summary(new.dat)

ggplot(new.dat, aes(x=Axis.1, y= Axis.2)) +
  geom_point(aes(color = Microbe, shape = Hour), position ="jitter") +
  facet_grid(~Hour)+
  theme_bw()+
  xlab("PCoA1 (59.1% Var. Expl.)")+ 	## !don't forget to update these moving forward!
  ylab("PCoA2 (32.6% Var. Expl.)")



###	#PCoA with Jaccard distances#	###
ord <- ordinate(VOC, method = "PCoA", distance = "jaccard")
plot_ordination( VOC, ord, color = "hour", shape = "microbe", type = "samples")
# split plot of compounds driving separation and samples in PC1/PC2. 
plot_ordination(VOC, ord, type = "samples", color = "hour", shape = "microbe", label = "rep")
###
###
PCs <- data.frame(scores(ord$vectors))
new.dat <- cbind(PCs, sample_data(VOC)$microbe, sample_data(VOC)$hour, sample_data(VOC)$rep) # make a new matrix
names(new.dat)[13:15] <- c("Microbe", "Hour", "Rep")
library(gdata)
new.dat$Microbe <- reorder.factor(new.dat$Microbe, new.order = c("SWD"))
new.dat$Hour <- reorder.factor(new.dat$Hour, new.order = c("24", "48"))
###
###
ggplot(new.dat, aes(x=Axis.1, y= Axis.2)) +
  geom_point(aes(color = Microbe, shape = Hour), position ="jitter") +
  facet_grid(~Hour)+
  theme_bw()+
  xlab("PCoA1 (78.6% Var. Expl.)")+ 
  ylab("PCoA2 (13.8% Var. Expl.)")
```

```{r}
######################
##  Linear Models   ##
######################

# try co-ercing days as categorical variable so I can use TukeyHSD
sample_data(VOC)$fhour <- factor(sample_data(VOC)$hour)
sample_data(VOC)$frep <- factor(sample_data(VOC)$rep)

str(sample_data(VOC))

fit <- lm(sample_sums(VOC)~ sample_data(VOC)$rep+sample_data(VOC)$hour)
anova(fit)
TukeyHSD(aov(fit), which="sample_data(VOC)$rep") 
TukeyHSD(aov(fit), which="sample_data(VOC)$hour")
```


```{r}
# Try with interactions in model

fit <- lm(sample_sums(VOC)~ sample_data(VOC)$hour*sample_data(VOC)$rep*sample_data(VOC)$microbe)
summary(fit)
######################################################################################################################################
Analysis of Variance Table

Response: sample_sums(VOC)
                                                                                      Df     Sum Sq    Mean Sq F value    Pr(>F)    
sample_data(VOC)$rep                                                           1 2.4626e+15 2.4626e+15 138.434 < 2.2e-16 ***
sample_data(VOC)$fhour                                                                  2 3.9403e+15 1.9702e+15 110.751 < 2.2e-16 ***
sample_data(VOC)$microbe                                                     2 4.0738e+15 2.0369e+15 114.502 < 2.2e-16 ***
sample_data(VOC)$rep:sample_data(VOC)$fhour                                     2 1.6148e+15 8.0739e+14  45.386 1.618e-12 ***
sample_data(VOC)$rep:sample_data(VOC)$microbe                        2 1.0694e+15 5.3468e+14  30.056 1.223e-09 ***
sample_data(VOC)$fhour:sample_data(VOC)$microbe                               4 2.0716e+15 5.1791e+14  29.114 3.385e-13 ***
sample_data(VOC)$rep:sample_data(VOC)$fhour:sample_data(VOC)$microbe  4 7.9485e+14 1.9871e+14  11.170 9.271e-07 ***
Residuals                                                                             57 1.0140e+15 1.7789e+13                      
#######################################################################################################################################

TukeyHSD(aov(fit), which="sample_data(VOC)$hour")
#######################################################################################################################################
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = fit)

$`sample_data(VOC)$fhour`
        diff      lwr      upr    p adj
1-0 11374762  8504020 14245503 0.00e+00
2-0 17493356 14622615 20364097 0.00e+00
2-1  6118594  3247853  8989336 1.08e-05
#######################################################################################################################################

TukeyHSD(aov(fit), which="sample_data(VOC)$rep")
#############################################################
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = fit)

$`sample_data(VOC)$rep`
               diff     lwr      upr p adj
normal-low 11543802 9579121 13508483     0
#############################################################

TukeyHSD(aov(fit), which="sample_data(VOC)$microbe.treatmemt")
###########################
returns NaNs
Fit: aov(formula = fit)

$<NA>
     diff lwr upr p adj

Warning message:
In qtukey(conf.level, length(means), x$df.residual) : NaNs produced
##################################################################

# Maybe if we remove day from the formula and reduce to only one sample day (2), it will work

DayTwo <- subset_samples(VOC, day=="2") 

fit <- lm(sample_sums(DayTwo)~ sample_data(DayTwo)$rep * sample_data(DayTwo)$microbe)
##########################################################################################################
Analysis of Variance Table

Response: sample_sums(DayTwo)
                                                                      Df     Sum Sq    Mean Sq F value    Pr(>F)    
sample_data(DayTwo)$rep                                        1 2.6684e+15 2.6684e+15  82.249 2.479e-08 ***
sample_data(DayTwo)$microbe                                  2 4.5758e+15 2.2879e+15  70.521 1.614e-09 ***
sample_data(DayTwo)$rep:sample_data(DayTwo)$microbe  2 1.3896e+15 6.9481e+14  21.416 1.354e-05 ***
Residuals                                                             19 6.1642e+14 3.2443e+13                      
########################################################################################################################

TukeyHSD(aov(fit), which="sample_data(DayTwo)$microbe.treatmemt")
## NaNs again


#############
# PERMANOVA #
#############

df = as(sample_data(VOC), "data.frame") # coerce to a data frame named df
d = distance(VOC, "bray") # make a dissimilarity matrix named d
names(df)[4] <- c("Microbe")
names(df)[6] <- c("Nectar")
names(df)[8] <- c("Day")
library(gdata)
df$Microbe <- reorder.factor(df$Microbe, new.order = c("MrAa", "Aa", "Mr"))
df$Nectar <- reorder.factor(df$Nectar, new.order = c("normal", "low"))
df$Day <- reorder.factor(df$Day, new.order = c("0", "1", "2"))

fit = adonis(d ~ Nectar * Day * Microbe, df)
b_test <-betadisper(d, group=df$Microbe, type="median")
b_test

#############################################################################
        Homogeneity of multivariate dispersions

Call: betadisper(d = d, group = df$Microbe, type = "median")

No. of Positive Eigenvalues: 39
No. of Negative Eigenvalues: 35

Average distance to median:
  MrAa     Aa     Mr 
0.4380 0.5006 0.4530 

Eigenvalues for PCoA axes:
(Showing 8 of 74 eigenvalues)
 PCoA1  PCoA2  PCoA3  PCoA4  PCoA5  PCoA6  PCoA7  PCoA8 
7.6596 5.8000 2.6695 2.3007 1.2038 0.9516 0.7906 0.6088 
###############################################################################
 
TukeyHSD(b_test)
#################################################################################
   Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$`group`
               diff        lwr        upr     p adj
Mr-Aa   -0.04755245 -0.1514047 0.05629975 0.5197828
MrAa-Aa -0.06261575 -0.1531520 0.02792050 0.2295835
MrAa-Mr -0.01506329 -0.1168173 0.08669066 0.9332236
###############################################################################

Call:
adonis(formula = d ~ Nectar * Day * Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                   Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar              1    2.9074  2.9074  28.726 0.12710  0.001 ***
Day                 1    3.4325  3.4325  33.914 0.15005  0.001 ***
Microbe             2    5.1239  2.5620  25.313 0.22399  0.001 ***
Nectar:Day          1    1.1653  1.1653  11.514 0.05094  0.001 ***
Nectar:Microbe      2    1.1420  0.5710   5.642 0.04992  0.001 ***
Day:Microbe         2    2.1837  1.0918  10.788 0.09546  0.001 ***
Nectar:Day:Microbe  2    0.5442  0.2721   2.689 0.02379  0.005 ** 
Residuals          63    6.3764  0.1012         0.27874           
Total              74   22.8755                 1.00000     
##############################################################################

fit = adonis(d ~ Nectar + Day + Microbe, df)
##################################################################################
Call:
adonis(formula = d ~ Nectar + Day + Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar     1    2.9074  2.9074  17.834 0.12710  0.001 ***
Day        1    3.4325  3.4325  21.055 0.15005  0.001 ***
Microbe    2    5.1239  2.5620  15.715 0.22399  0.001 ***
Residuals 70   11.4116  0.1630         0.49886           
Total     74   22.8755                 1.00000   
######################################################################################

#
##
###
 
# Now re-do with jaccard distances

df = as(sample_data(VOC), "data.frame") # coerce to a data frame named df
d = distance(VOC, "jaccard") # make a dissimilarity matrix named d
names(df)[4] <- c("Microbe")
names(df)[6] <- c("Nectar")
names(df)[8] <- c("Day")
library(gdata)
df$Microbe <- reorder.factor(df$Microbe, new.order = c("MrAa", "Aa", "Mr"))
df$Nectar <- reorder.factor(df$Nectar, new.order = c("normal", "low"))
df$Day <- reorder.factor(df$Day, new.order = c("0", "1", "2"))

fit = adonis(d ~ Nectar * Day * Microbe, df)
b_test <-betadisper(d, group=df$Microbe, type="median")
b_test

#############################################################################
        Homogeneity of multivariate dispersions

Call: betadisper(d = d, group = df$Microbe, type = "median")

No. of Positive Eigenvalues: 53
No. of Negative Eigenvalues: 21

Average distance to median:
    Aa     Mr   MrAa 
0.5556 0.5226 0.5081 

Eigenvalues for PCoA axes:
(Showing 8 of 74 eigenvalues)
 PCoA1  PCoA2  PCoA3  PCoA4  PCoA5  PCoA6  PCoA7  PCoA8 
6.8959 5.2154 2.7848 2.4644 1.7195 1.3511 0.8946 0.8039 
###############################################################################
 
TukeyHSD(b_test)
#################################################################################
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$`group`
               diff         lwr        upr     p adj
Mr-Aa   -0.03299930 -0.11741041 0.05141181 0.6197301
MrAa-Aa -0.04756155 -0.12114944 0.02602635 0.2754873
MrAa-Mr -0.01456225 -0.09726791 0.06814341 0.9069053
###############################################################################

b_test <-betadisper(d, group=df$Nectar, type="median")
b_test
##############################################################
        Homogeneity of multivariate dispersions

Call: betadisper(d = d, group = df$Nectar, type = "median")

No. of Positive Eigenvalues: 53
No. of Negative Eigenvalues: 21

Average distance to median:
   low normal 
0.5576 0.5624 

Eigenvalues for PCoA axes:
(Showing 8 of 74 eigenvalues)
 PCoA1  PCoA2  PCoA3  PCoA4  PCoA5  PCoA6  PCoA7  PCoA8 
6.8959 5.2154 2.7848 2.4644 1.7195 1.3511 0.8946 0.8039 
###########################################################

TukeyHSD(b_test)
########################################################
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$`group`
                  diff         lwr        upr     p adj
normal-low 0.004804244 -0.03892604 0.04853453 0.8272983
############################################################


b_test <-betadisper(d, group=df$Day, type="median")
######################################################################
  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = distances ~ group, data = df)

$`group`
          diff         lwr        upr     p adj
1-0 0.02413893 -0.05659384 0.10487170 0.7551262
2-0 0.02621599 -0.05451678 0.10694876 0.7182120
2-1 0.00207706 -0.07865571 0.08280983 0.9979123
###################################################################

summary(fit)
############################################################################
             Length Class  Mode   
aov.tab         6   anova  list   
call            3   -none- call   
coefficients    0   -none- NULL   
coef.sites    900   -none- numeric
f.perms      6993   -none- numeric
model.matrix  900   -none- numeric
terms           3   terms  call     
#########################################################################

fit
#########################################################################
Call:
adonis(formula = d ~ Nectar * Day * Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                   Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar              1    2.9068 2.90676 19.0040 0.10799  0.001 ***
Day                 1    3.0846 3.08457 20.1665 0.11460  0.001 ***
Microbe             2    4.7994 2.39969 15.6889 0.17831  0.001 ***
Nectar:Day          1    1.3590 1.35901  8.8850 0.05049  0.001 ***
Nectar:Microbe      2    1.7147 0.85735  5.6052 0.06370  0.001 ***
Day:Microbe         2    2.4705 1.23525  8.0759 0.09178  0.001 ***
Nectar:Day:Microbe  2    0.9454 0.47271  3.0905 0.03512  0.001 ***
Residuals          63    9.6362 0.15295         0.35800           
Total              74   26.9165                 1.00000            
########################################################################

fit = adonis(d ~ Nectar + Day + Microbe, df)

Call:
adonis(formula = d ~ Nectar + Day + Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar     1    2.9068 2.90676  12.618 0.10799  0.001 ***
Day        1    3.0846 3.08457  13.390 0.11460  0.001 ***
Microbe    2    4.7994 2.39969  10.417 0.17831  0.001 ***
Residuals 70   16.1258 0.23037         0.59910           
Total     74   26.9165                 1.00000        
##################################################################3

###
##
#
#
##
###

Mrsonly <- subset_samples(VOC, microbe!="Aa") 

df = as(sample_data(Mrsonly), "data.frame") # coerce to a data frame named df
d = distance(Mrsonly, "bray") # make a dissimilarity matrix named d
names(df)[4] <- c("Microbe")
names(df)[6] <- c("Nectar")
names(df)[8] <- c("Day")
library(gdata)
df$Microbe <- reorder.factor(df$Microbe, new.order = c("MrAa", "Mr"))
df$Nectar <- reorder.factor(df$Nectar, new.order = c("normal", "low"))
df$Day <- reorder.factor(df$Day, new.order = c("0", "1", "2"))

fit = adonis(d ~ Nectar * Day * Microbe, df)

fit
#############################################################################
Call:
adonis(formula = d ~ Nectar * Day * Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

                   Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar              1    1.8002 1.80018 24.5420 0.16961  0.001 ***
Day                 2    3.4257 1.71285 23.3515 0.32276  0.001 ***
Microbe             1    0.2543 0.25426  3.4663 0.02396  0.023 *  
Nectar:Day          2    1.3179 0.65895  8.9835 0.12417  0.001 ***
Nectar:Microbe      1    0.1589 0.15886  2.1658 0.01497  0.090 .  
Day:Microbe         2    0.7418 0.37088  5.0563 0.06989  0.001 ***
Nectar:Day:Microbe  2    0.2746 0.13729  1.8717 0.02587  0.096 .  
Residuals          36    2.6406 0.07335         0.24879           
Total              47   10.6139                 1.00000           
#############################################################################

fit = adonis(d ~ Nectar + Day + Microbe, df)
##############################################################################
Call:
adonis(formula = d ~ Nectar + Day + Microbe, data = df) 

Permutation: free
Number of permutations: 999

Terms added sequentially (first to last)

          Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Nectar     1    1.8002 1.80018 15.0783 0.16961  0.001 ***
Day        2    3.4257 1.71285 14.3468 0.32276  0.001 ***
Microbe    1    0.2543 0.25426  2.1296 0.02396  0.115    
Residuals 43    5.1337 0.11939         0.48368           
Total     47   10.6139                 1.00000           
###############################################################################

###
##
#

#
##
###
```



#####################
# Diversity Indices #
#####################
```{r}
# Is there a difference in the number of different peaks (alpha-diversity) between treatments? Start with all days

# Force all peak area to round integers. Re-import data

abund <- round(abund[,-c(1:2)], digits = 0)
OTU <- otu_table(abund, taxa_are_rows=T) 

VOC <- phyloseq(OTU, TAX, SAMP)
VOC

plot_richness(VOC, x = "hour", measures = c("Observed", "Shannon", "Simpson"))

plot_richness(VOC, x = "rep", measures = c("Observed", "Shannon", "Simpson"))

fit <- lm(estimate_richness(VOC)$Shannon ~ sample_data(VOC)$hour)
anova(fit)
####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Shannon
#                                   Df Sum Sq Mean Sq F value Pr(>F)  
#sample_data(VOC)$microbe  2 0.7583 0.37916  2.8838 0.0624 .
#Residuals                          72 9.4665 0.13148                              
####################################################################################


fit <- lm(estimate_richness(VOC)$Observed ~ sample_data(VOC)$hour)
anova(fit)
#####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Observed
#                                   Df  Sum Sq Mean Sq F value    Pr(>F)    
#sample_data(VOC)$microbe  2  477.02 238.510  9.2143 0.0002735 ***
#Residuals                          72 1863.70  25.885                      
######################################################################################

fit <- lm(estimate_richness(VOC)$Simpson ~ sample_data(VOC)$hour)
anova(fit)
#####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Simpson
#                                   Df  Sum Sq  Mean Sq F value  Pr(>F)  
#sample_data(VOC)$microbe  2 0.16149 0.080744  3.5494 0.03387 *
#Residuals                          72 1.63791 0.022749                               
######################################################################################

###
##
# just for fun, what differences exist in diversity of chemicals between nectar concentrations?

fit <- lm(estimate_richness(VOC)$Shannon ~ sample_data(VOC)$rep)
anova(fit)
#####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Shannon
#                             Df  Sum Sq Mean Sq F value Pr(>F)
#sample_data(VOC)$rep  1  0.1989 0.19886  1.4479 0.2327
#Residuals                    73 10.0259 0.13734               
#####################################################################################

fit <- lm(estimate_richness(VOC)$Observed ~ sample_data(VOC)$rep)
anova(fit)
#####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Observed
#                             Df  Sum Sq Mean Sq F value   Pr(>F)   
#sample_data(VOC)$rep  1  229.75 229.752  7.9451 0.006202 **
#Residuals                    73 2110.97  28.917                    
#####################################################################################

fit <- lm(estimate_richness(VOC)$Simpson ~ sample_data(VOC)$rep)
anova(fit)
#####################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(VOC)$Simpson
#                             Df  Sum Sq  Mean Sq F value Pr(>F)
#sample_data(VOC)$rep  1 0.01421 0.014206  0.5809 0.4484
#Residuals                    73 1.78519 0.024455               
#####################################################################################
###
##
# 
##
###
```

# repeat diversity indices calcs with controls and blanks excluded
```{r}
NoZero <- subset_samples(VOC, rep!="C01"& rep!="C02"& rep!="C03"& rep!="B01")

plot_richness(NoZero, x = "hour", measures = c("Observed", "Shannon", "Simpson"))

plot_richness(NoZero, x = "rep", measures = c("Observed", "Shannon", "Simpson"))

fit <- lm(estimate_richness(NoZero)$Shannon ~ sample_data(NoZero)$hour)
anova(fit)
#############################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(NoZero)$Shannon
#                                      Df Sum Sq  Mean Sq F value  Pr(>F)  
#sample_data(NoZero)$microbe  2 0.4031 0.201558  2.5438 0.08934 .
#Residuals                             47 3.7241 0.079235                  
##############################################################################################


fit <- lm(estimate_richness(NoZero)$Observed ~ sample_data(NoZero)$hour)
anova(fit)
###############################################################################################
#Analysis of Variance Table
#
#Response: estimate_richness(NoZero)$Observed
#                                      Df Sum Sq Mean Sq F value    Pr(>F)    
#sample_data(NoZero)$microbe  2 420.01 210.003  26.676 1.813e-08 ***
#Residuals                             47 369.99   7.872                                        
################################################################################################

fit <- lm(estimate_richness(NoZero)$Simpson ~ sample_data(NoZero)$hour)
anova(fit)
#################################################################################################
#Analysis of Variance Table
#Response: estimate_richness(NoZero)$Simpson
#                                      Df  Sum Sq  Mean Sq F value   Pr(>F)   
#sample_data(NoZero)$microbe  2 0.14082 0.070409  6.3029 0.003759 **
#Residuals                             47 0.52504 0.011171                          
##################################################################################################

###
##
# again with nectar conc

fit <- lm(estimate_richness(NoZero)$Shannon ~ sample_data(NoZero)$rep)
anova(fit)
#################################################################################################
#Analysis of Variance Table
#Response: estimate_richness(NoZero)$Shannon
#                                Df Sum Sq Mean Sq F value  Pr(>F)  
#sample_data(NoZero)$rep  1 0.3487 0.34865  4.4291 0.04059 *
#Residuals                       48 3.7785 0.07872                  
#################################################################################################

fit <- lm(estimate_richness(NoZero)$Observed ~ sample_data(NoZero)$rep)
anova(fit)
#################################################################################################
#Analysis of Variance Table
#Response: estimate_richness(NoZero)$Observed
#                                Df Sum Sq Mean Sq F value    Pr(>F)    
#sample_data(NoZero)$rep  1 165.83 165.831  12.753 0.0008204 ***
#Residuals                       48 624.17  13.004                   
#################################################################################################

fit <- lm(estimate_richness(NoZero)$Simpson ~ sample_data(NoZero)$rep)
anova(fit)
#################################################################################################
#Analysis of Variance Table
#Response: estimate_richness(NoZero)$Simpson
#                                Df  Sum Sq  Mean Sq F value   Pr(>F)   
#sample_data(NoZero)$rep  1 0.10357 0.103566   8.841 0.004596 **
#Residuals                       48 0.56229 0.011714                    
#################################################################################################
```


############################
# Neg Binomial Permutation #
############################
```{r}
# which compounds differentiate our groups? control and blanks.
install.packages("XVector")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
BiocManager::install(c("GenomicFeatures", "AnnotationDbi"))
BiocManager::install("DESeq2")
BiocManager::valid()
BiocManager::install("sessionInfo")

NoZero <- subset_samples(VOC, rep!="C01"& rep!="C02"& rep!="C03"& rep!="B01")
deobj <- phyloseq_to_deseq2(NoZero, ~ hour + rep)
diagdds <- DESeq(deobj, test="Wald", fitType="local")
```

```{r}
res = results(diagdds, contrast = c("rep", "24", "48"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("microbe", "Aa", "MrAa"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("microbe", "Mr", "MrAa"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("rep", "normal", "low"), cooksCutoff = FALSE)

alpha = 0.01
sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(NoZero)[rownames(sigtab), ], "matrix"))
x = tapply(sigtab$log2FoldChange, sigtab$Name, function(x) max(x))
x = sort(x, TRUE)
sigtab$Compound = factor(as.character(sigtab$Name), levels=names(x))

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating Mr and Aa samples")+
  theme_bw()

res = results(diagdds, contrast = c("microbe", "Aa", "Mr"), cooksCutoff = FALSE)
################################################################################
           baseMean log2FoldChange     lfcSE       stat        pvalue
Peak_01  172970.710       8.547149 1.0585296   8.074549  6.772636e-16
Peak_02  229723.715      -3.975209 0.9038066  -4.398296  1.091039e-05
Peak_03  108640.735      -4.842292 1.7052150  -2.839696  4.515656e-03
Peak_04  114300.257      -2.401561 0.2646517  -9.074420  1.142848e-19
Peak_05    6429.938      -5.176677 1.5285077  -3.386752  7.072519e-04
Peak_06 3723194.815      -4.673254 0.7784913  -6.002963  1.937489e-09
Peak_08   27411.692      -5.753289 1.3866688  -4.149000  3.339305e-05
Peak_10  290087.858      -6.341055 0.7407218  -8.560643  1.122396e-17
Peak_11    9144.101     -30.000000 1.5551940 -19.290198  6.492447e-83
Peak_13 3876312.995      -7.289726 0.6633077 -10.989962  4.271072e-28
Peak_14   16839.414      -2.005219 0.7378130  -2.717787  6.572010e-03
Peak_16  567316.293       2.522966 0.3722113   6.778318  1.215830e-11
Peak_17   41154.421     -18.705320 0.6259842 -29.881458 3.427297e-196
Peak_20  129072.733      -1.733230 0.4030592  -4.300188  1.706533e-05
Peak_21   22035.125       2.314304 0.8011196   2.888837  3.866699e-03
Peak_22    5097.497       4.715515 1.7487425   2.696518  7.006866e-03
Peak_25    4103.271       7.378659 1.7758910   4.154906  3.254217e-05
Peak_28 1345142.579       2.110005 0.7666845   2.752117  5.921139e-03
Peak_32  145114.357       1.366084 0.2527009   5.405933  6.447198e-08
Peak_33    7609.200      -4.781830 1.2156448  -3.933575  8.369170e-05
Peak_34  292863.350      -8.815999 0.9091207  -9.697281  3.096397e-22
                 padj Peak_ID                   Name               Compound
Peak_01  2.612303e-15 Peak_01               isoprene               isoprene
Peak_02  2.678006e-05 Peak_02           acetaldehyde           acetaldehyde
Peak_03  6.773484e-03 Peak_03       isobutylaldehyde       isobutylaldehyde
Peak_04  6.171378e-19 Peak_04          2-methylfuran          2-methylfuran
Peak_05  1.193488e-03 Peak_05                   EtAc                   EtAc
Peak_06  5.812468e-09 Peak_06                ethanol                ethanol
Peak_08  6.440088e-05 Peak_08             1-propanol             1-propanol
Peak_10  5.050780e-17 Peak_10             isobutanol             isobutanol
Peak_11  8.764804e-82 Peak_11        isoamyl acetate        isoamyl acetate
Peak_13  3.843964e-27 Peak_13 2and3-methyl-1-butanol 2and3-methyl-1-butanol
Peak_14  8.872214e-03 Peak_14  3-methyl-3-buten-1-ol  3-methyl-3-buten-1-ol
Peak_16  4.103427e-11 Peak_16                acetoin                acetoin
Peak_17 9.253702e-195 Peak_17          4-penten-1-ol          4-penten-1-ol
Peak_20  3.839699e-05 Peak_20              1-hexanol              1-hexanol
Peak_21  6.141227e-03 Peak_21              unknown 2              unknown 2
Peak_22  9.008827e-03 Peak_22              unknown 3              unknown 3
Peak_25  6.440088e-05 Peak_25              3-octanol              3-octanol
Peak_28  8.414250e-03 Peak_28      2-ethyl-1-hexanol      2-ethyl-1-hexanol
Peak_32  1.740743e-07 Peak_32        2-furanmethanol        2-furanmethanol
Peak_33  1.506451e-04 Peak_33              1-nonanol              1-nonanol
Peak_34  2.090068e-21 Peak_34    2-phenethyl alcohol    2-phenethyl alcohol
############################################################################################


res = results(diagdds, contrast = c("microbe", "Aa", "MrAa"), cooksCutoff = FALSE)

sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(NoZero)[rownames(sigtab), ], "matrix"))
x = tapply(sigtab$log2FoldChange, sigtab$Name, function(x) max(x))
x = sort(x, TRUE)
sigtab$Compound = factor(as.character(sigtab$Name), levels=names(x))

res = results(diagdds, contrast = c("microbe", "Aa", "MrAa"), cooksCutoff = FALSE)
#################################################################################################
           baseMean log2FoldChange     lfcSE       stat        pvalue
Peak_01  172970.710       2.571465 0.8817382   2.916359  3.541429e-03
Peak_02  229723.715      -3.665710 0.7529259  -4.868620  1.123805e-06
Peak_03  108640.735      -5.588084 1.4205535  -3.933737  8.363530e-05
Peak_04  114300.257      -1.954784 0.2204682  -8.866513  7.547219e-19
Peak_05    6429.938      -5.568559 1.2732440  -4.373521  1.222586e-05
Peak_06 3723194.815      -4.858056 0.6485301  -7.490871  6.841797e-14
Peak_08   27411.692      -6.119115 1.1551846  -5.297089  1.176636e-07
Peak_10  290087.858      -6.411193 0.6170658 -10.389805  2.759179e-25
Peak_11    9144.101     -29.958661 1.3176789 -22.735935 1.977173e-114
Peak_12   24965.215       2.084710 0.7391396   2.820455  4.795563e-03
Peak_13 3876312.995      -7.070071 0.5525753 -12.794764  1.753838e-37
Peak_17   41154.421     -16.979344 0.5759060 -29.482839 4.778429e-191
Peak_22    5097.497       7.400060 1.4572996   5.077926  3.815765e-07
Peak_32  145114.357       2.013536 0.2105093   9.565068  1.121272e-21
Peak_33    7609.200      -3.809031 1.0126839  -3.761323  1.690170e-04
Peak_34  292863.350      -7.024164 0.7573479  -9.274685  1.781448e-20
                 padj Peak_ID                   Name               Compound
Peak_01  6.374572e-03 Peak_01               isoprene               isoprene
Peak_02  2.758430e-06 Peak_02           acetaldehyde           acetaldehyde
Peak_03  1.737041e-04 Peak_03       isobutylaldehyde       isobutylaldehyde
Peak_04  2.911070e-18 Peak_04          2-methylfuran          2-methylfuran
Peak_05  2.750818e-05 Peak_05                   EtAc                   EtAc
Peak_06  2.309106e-13 Peak_06                ethanol                ethanol
Peak_08  3.529909e-07 Peak_08             1-propanol             1-propanol
Peak_10  1.862446e-24 Peak_10             isobutanol             isobutanol
Peak_11 2.669183e-113 Peak_11        isoamyl acetate        isoamyl acetate
Peak_12  8.092513e-03 Peak_12   3-methyl-2-heptanone   3-methyl-2-heptanone
Peak_13  1.578454e-36 Peak_13 2and3-methyl-1-butanol 2and3-methyl-1-butanol
Peak_17 1.290176e-189 Peak_17          4-penten-1-ol          4-penten-1-ol
Peak_22  1.030257e-06 Peak_22              unknown 3              unknown 3
Peak_32  6.054871e-21 Peak_32        2-furanmethanol        2-furanmethanol
Peak_33  3.259613e-04 Peak_33              1-nonanol              1-nonanol
Peak_34  8.016517e-20 Peak_34    2-phenethyl alcohol    2-phenethyl alcohol
##############################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating MrAa and Aa samples")+
  theme_bw()

res = results(diagdds, contrast = c("microbe", "Mr", "MrAa"), cooksCutoff = FALSE)
....
sigtab
######################################################################################
         baseMean log2FoldChange     lfcSE      stat       pvalue         padj
Peak_01 172970.71      -5.975684 1.0262266 -5.822967 5.781184e-09 1.560920e-07
Peak_16 567316.29      -1.942773 0.3608512 -5.383860 7.290533e-08 9.842219e-07
Peak_17  41154.42       1.725977 0.4026773  4.286252 1.817125e-05 1.635413e-04
Peak_20 129072.73       1.564386 0.3907546  4.003500 6.241208e-05 4.212815e-04
        Peak_ID          Name      Compound
Peak_01 Peak_01      isoprene      isoprene
Peak_16 Peak_16       acetoin       acetoin
Peak_17 Peak_17 4-penten-1-ol 4-penten-1-ol
Peak_20 Peak_20     1-hexanol     1-hexanol
###################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating MrAa and Mr samples")+
  theme_bw()

res = results(diagdds, contrast = c("rep", "normal", "low"), cooksCutoff = FALSE)
....
sigtab
########################################################################################
           baseMean log2FoldChange     lfcSE      stat       pvalue
Peak_01  172970.710     -3.8740203 0.8131465 -4.764234 1.895721e-06
Peak_04  114300.257      0.6093800 0.2033063  2.997349 2.723389e-03
Peak_07  114857.656      0.5512379 0.1542863  3.572824 3.531528e-04
Peak_16  567316.293     -1.3049309 0.2859393 -4.563665 5.026836e-06
Peak_17   41154.421      1.1060167 0.3789650  2.918520 3.516979e-03
Peak_20  129072.733     -2.2140437 0.3096392 -7.150398 8.652659e-13
Peak_22    5097.497      5.5012743 1.3439470  4.093371 4.251460e-05
Peak_23    3259.009     13.8798951 1.2563398 11.047883 2.244455e-28
Peak_25    4103.271      5.2195171 1.3586300  3.841750 1.221601e-04
Peak_27   11562.826     -3.3162389 0.8531968 -3.886839 1.015579e-04
Peak_28 1345142.579      1.9853791 0.5889831  3.370859 7.493414e-04
Peak_32  145114.357      1.9812350 0.1941255 10.205950 1.864863e-24
                padj Peak_ID                           Name
Peak_01 1.279612e-05 Peak_01                       isoprene
Peak_04 6.684682e-03 Peak_04                  2-methylfuran
Peak_07 1.059458e-03 Peak_07              2,5-dimethylfuran
Peak_16 2.714491e-05 Peak_16                        acetoin
Peak_17 7.913202e-03 Peak_17                  4-penten-1-ol
Peak_20 7.787393e-12 Peak_20                      1-hexanol
Peak_22 1.913157e-04 Peak_22                      unknown 3
Peak_23 6.060028e-27 Peak_23 2-ethylhexyl ester acetic acid
Peak_25 4.122904e-04 Peak_25                      3-octanol
Peak_27 3.917234e-04 Peak_27                     1-heptanol
Peak_28 2.023222e-03 Peak_28              2-ethyl-1-hexanol
Peak_32 2.517565e-23 Peak_32                2-furanmethanol
                              Compound
Peak_01                       isoprene
Peak_04                  2-methylfuran
Peak_07              2,5-dimethylfuran
Peak_16                        acetoin
Peak_17                  4-penten-1-ol
Peak_20                      1-hexanol
Peak_22                      unknown 3
Peak_23 2-ethylhexyl ester acetic acid
Peak_25                      3-octanol
Peak_27                     1-heptanol
Peak_28              2-ethyl-1-hexanol
Peak_32                2-furanmethanol
#######################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating 1.5 and 15% samples")+
  theme_bw()
###
##
#

# 
##
###

deobj <- phyloseq_to_deseq2(NoZero, ~ rep * microbe)
diagdds = DESeq(deobj, test="Wald", fitType="local")


res = results(diagdds, contrast = c("microbe", "Aa", "Mr"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("microbe", "Aa", "MrAa"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("microbe", "Mr", "MrAa"), cooksCutoff = FALSE)

res = results(diagdds, contrast = c("rep", "normal", "low"), cooksCutoff = FALSE)

sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(NoZero)[rownames(sigtab), ], "matrix"))
x = tapply(sigtab$log2FoldChange, sigtab$Name, function(x) max(x))
x = sort(x, TRUE)
sigtab$Compound = factor(as.character(sigtab$Name), levels=names(x))
sigtab #(res = results(diagdds, contrast = c("microbe", "Aa", "Mr"), cooksCutoff = FALSE))
#######################################################################################
           baseMean log2FoldChange     lfcSE       stat       pvalue
Peak_01  172970.710       7.096023 1.1545505   6.146134 7.939409e-10
Peak_02  229723.715      -3.065363 1.1195108  -2.738127 6.179021e-03
Peak_04  114300.257      -2.340912 0.2664793  -8.784594 1.569303e-18
Peak_05    6429.938     -25.779765 1.8217390 -14.151185 1.836371e-45
Peak_06 3723194.815      -3.935595 0.9402285  -4.185785 2.841819e-05
Peak_08   27411.692      -4.667917 1.7005505  -2.744945 6.052106e-03
Peak_10  290087.858      -5.949781 0.8952180  -6.646181 3.007955e-11
Peak_11    9144.101     -27.910717 2.0154424 -13.848432 1.300201e-43
Peak_13 3876312.995      -7.187288 0.7899597  -9.098297 9.175920e-20
Peak_16  567316.293       3.844822 0.3023751  12.715406 4.855814e-37
Peak_17   41154.421     -16.312931 0.8026720 -20.323284 8.003947e-92
Peak_20  129072.733      -2.086494 0.4767748  -4.376268 1.207285e-05
Peak_21   22035.125       2.650081 0.9777067   2.710507 6.718035e-03
Peak_22    5097.497       5.745642 1.8583159   3.091854 1.989105e-03
Peak_23    3259.009       5.806242 2.0681328   2.807480 4.993078e-03
Peak_25    4103.271      27.856223 2.0552502  13.553689 7.534581e-42
Peak_28 1345142.579       2.801856 0.9128899   3.069216 2.146211e-03
Peak_32  145114.357       1.086914 0.2667270   4.075004 4.601353e-05
Peak_33    7609.200     -14.585211 1.3573799 -10.745121 6.248010e-27
Peak_34  292863.350      -9.855555 1.1127010  -8.857326 8.195693e-19
                padj Peak_ID                           Name
Peak_01 1.948764e-09 Peak_01                       isoprene
Peak_02 8.780714e-03 Peak_02                   acetaldehyde
Peak_04 4.707908e-18 Peak_04                  2-methylfuran
Peak_05 2.479101e-44 Peak_05                           EtAc
Peak_06 5.902240e-05 Peak_06                        ethanol
Peak_08 8.780714e-03 Peak_08                     1-propanol
Peak_10 8.121479e-11 Peak_10                     isobutanol
Peak_11 1.170181e-42 Peak_11                isoamyl acetate
Peak_13 3.539284e-19 Peak_13         2and3-methyl-1-butanol
Peak_16 2.622140e-36 Peak_16                        acetoin
Peak_17 2.161066e-90 Peak_17                  4-penten-1-ol
Peak_20 2.716392e-05 Peak_20                      1-hexanol
Peak_21 9.069347e-03 Peak_21                      unknown 2
Peak_22 3.580388e-03 Peak_22                      unknown 3
Peak_23 7.930182e-03 Peak_23 2-ethylhexyl ester acetic acid
Peak_25 5.085842e-41 Peak_25                      3-octanol
Peak_28 3.621731e-03 Peak_28              2-ethyl-1-hexanol
Peak_32 8.874039e-05 Peak_32                2-furanmethanol
Peak_33 2.811605e-26 Peak_33                      1-nonanol
Peak_34 2.766046e-18 Peak_34            2-phenethyl alcohol
#####################################################################################
ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating Mr and Aa samples")+
  theme_bw()

res = results(diagdds, contrast = c("microbe", "Aa", "MrAa"), cooksCutoff = FALSE)
...
sigtab # above
########################################################################################
           baseMean log2FoldChange     lfcSE       stat       pvalue
Peak_02  229723.715      -3.331702 1.1195106  -2.976034 2.920022e-03
Peak_04  114300.257      -1.369638 0.2664813  -5.139715 2.751561e-07
Peak_05    6429.938     -26.884550 1.8217212 -14.757774 2.741807e-49
Peak_06 3723194.815      -4.712543 0.9402285  -5.012126 5.383196e-07
Peak_08   27411.692      -5.750044 1.7005472  -3.381290 7.214625e-04
Peak_10  290087.858      -6.878734 0.8952175  -7.683868 1.543552e-14
Peak_11    9144.101     -28.126256 2.0154385 -13.955402 2.916506e-44
Peak_13 3876312.995      -7.630838 0.7899597  -9.659782 4.468138e-22
Peak_17   41154.421     -15.192101 0.8026751 -18.926838 6.855649e-80
Peak_22    5097.497      29.644245 1.9664691  15.074859 2.370199e-51
Peak_23    3259.009       6.260053 2.0681328   3.026911 2.470671e-03
Peak_32  145114.357       1.977423 0.2667332   7.413484 1.230238e-13
Peak_33    7609.200     -14.125086 1.3573797 -10.406142 2.324515e-25
Peak_34  292863.350      -8.497808 1.1127012  -7.637098 2.221728e-14
                padj Peak_ID                           Name
Peak_02 5.631472e-03 Peak_02                   acetaldehyde
Peak_04 7.429215e-07 Peak_04                  2-methylfuran
Peak_05 2.467626e-48 Peak_05                           EtAc
Peak_06 1.321330e-06 Peak_06                        ethanol
Peak_08 1.623291e-03 Peak_08                     1-propanol
Peak_10 5.953699e-14 Peak_10                     isobutanol
Peak_11 1.968641e-43 Peak_11                isoamyl acetate
Peak_13 2.010662e-21 Peak_13         2and3-methyl-1-butanol
Peak_17 1.851025e-78 Peak_17                  4-penten-1-ol
Peak_22 3.199768e-50 Peak_22                      unknown 3
Peak_23 5.131393e-03 Peak_23 2-ethylhexyl ester acetic acid
Peak_32 3.690713e-13 Peak_32                2-furanmethanol
Peak_33 1.255238e-24 Peak_33                      1-nonanol
Peak_34 7.498332e-14 Peak_34            2-phenethyl alcohol
###########################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating MrAa and Aa samples")+
  theme_bw()

res = results(diagdds, contrast = c("microbe", "Mr", "MrAa"), cooksCutoff = FALSE)
....
sigtab # above
################################################################################################
          baseMean log2FoldChange     lfcSE       stat       pvalue
Peak_01 172970.710     -6.0328197 1.0885299  -5.542172 2.987430e-08
Peak_04 114300.257      0.9712743 0.2511971   3.866583 1.103710e-04
Peak_16 567316.293     -3.1554548 0.2850826 -11.068564 1.782342e-28
Peak_17  41154.421      1.1208304 0.3319453   3.376551 7.340077e-04
Peak_20 129072.733      1.7197295 0.4495007   3.825866 1.303133e-04
Peak_22   5097.497     23.8986036 1.8671240  12.799687 1.646129e-37
Peak_25   4103.271    -24.2355019 1.9498674 -12.429308 1.811971e-35
Peak_32 145114.357      0.8905089 0.2514846   3.541008 3.986008e-04
                padj Peak_ID            Name        Compound
Peak_01 2.016515e-07 Peak_01        isoprene        isoprene
Peak_04 5.864098e-04 Peak_04   2-methylfuran   2-methylfuran
Peak_16 1.604108e-27 Peak_16         acetoin         acetoin
Peak_17 2.477276e-03 Peak_17   4-penten-1-ol   4-penten-1-ol
Peak_20 5.864098e-04 Peak_20       1-hexanol       1-hexanol
Peak_22 4.444549e-36 Peak_22       unknown 3       unknown 3
Peak_25 2.446161e-34 Peak_25       3-octanol       3-octanol
Peak_32 1.537460e-03 Peak_32 2-furanmethanol 2-furanmethanol
####################################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating MrAa and Mr samples")+
  theme_bw()






sample_data(NoZero)$TreatNect <- paste(sample_data(NoZero)$microbe, 
	sample_data(NoZero)$rep)

deobj <- phyloseq_to_deseq2(NoZero, ~ TreatNect)
diagdds = DESeq(deobj, test="Wald", fitType="local")


res = results(diagdds, contrast = c("TreatNect", "MrAa normal", "MrAa low"), cooksCutoff = FALSE)

sigtab = res[which(res$padj < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(NoZero)[rownames(sigtab), ], "matrix"))
x = tapply(sigtab$log2FoldChange, sigtab$Name, function(x) max(x))
x = sort(x, TRUE)
sigtab$Compound = factor(as.character(sigtab$Name), levels=names(x))
sigtab
######################################################################################################
          baseMean log2FoldChange     lfcSE      stat       pvalue
Peak_01 172970.710      -4.608430 1.0884792 -4.233824 2.297505e-05
Peak_04 114300.257       1.286420 0.2511921  5.121262 3.034979e-07
Peak_16 567316.293      -1.951653 0.2850748 -6.846108 7.588645e-12
Peak_20 129072.733      -2.202685 0.4495016 -4.900283 9.569858e-07
Peak_22   5097.497      27.978724 1.8664369 14.990447 8.478010e-51
Peak_23   3259.009      31.417225 1.8400424 17.074185 2.310273e-65
Peak_32 145114.357       2.140776 0.2514650  8.513217 1.691735e-17
                padj Peak_ID                           Name
Peak_01 8.861806e-05 Peak_01                       isoprene
Peak_04 1.638889e-06 Peak_04                  2-methylfuran
Peak_16 5.122335e-11 Peak_16                        acetoin
Peak_20 4.306436e-06 Peak_20                      1-hexanol
Peak_22 1.144531e-49 Peak_22                      unknown 3
Peak_23 6.237737e-64 Peak_23 2-ethylhexyl ester acetic acid
Peak_32 1.522562e-16 Peak_32                2-furanmethanol
#####################################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating MrAa samples in 1.5 vs 15% nectar")+
  theme_bw()


res = results(diagdds, contrast = c("TreatNect", "Mr normal", "Mr low"), cooksCutoff = FALSE)
...
sigtab
######################################################################################
          baseMean log2FoldChange     lfcSE      stat       pvalue
Peak_01 172970.710     -22.905266 2.3739801 -9.648466 4.989656e-22
Peak_17  41154.421       2.909908 0.5748958  5.061627 4.156946e-07
Peak_20 129072.733      -3.504705 0.7785615 -4.501513 6.747147e-06
Peak_23   3259.009      32.650270 3.0536306 10.692279 1.106190e-26
Peak_25   4103.271      28.182886 3.2511537  8.668580 4.375421e-18
                padj Peak_ID                           Name
Peak_01 6.736035e-21 Peak_01                       isoprene
Peak_17 2.805938e-06 Peak_17                  4-penten-1-ol
Peak_20 3.643459e-05 Peak_20                      1-hexanol
Peak_23 2.986713e-25 Peak_23 2-ethylhexyl ester acetic acid
Peak_25 3.937879e-17 Peak_25                      3-octanol
########################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating Mr samples in 1.5 vs 15% nectar")+
  theme_bw()

res = results(diagdds, contrast = c("TreatNect", "Aa normal", "Aa low"), cooksCutoff = FALSE)
################################################################################################3
          baseMean log2FoldChange     lfcSE      stat       pvalue
Peak_05   6429.938      24.011186 1.8217433 13.180335 1.138846e-39
Peak_16 567316.293      -2.122503 0.3023682 -7.019598 2.225081e-12
Peak_20 129072.733      -1.865983 0.4767799 -3.913720 9.088513e-05
Peak_23   3259.009      24.226971 1.9649649 12.329468 6.286066e-35
Peak_27  11562.826      -4.370947 1.3565890 -3.222013 1.272934e-03
Peak_32 145114.357       2.187298 0.2667083  8.201085 2.382267e-16
Peak_33   7609.200      11.707649 1.3573957  8.625082 6.404697e-18
                padj Peak_ID                           Name
Peak_05 3.074885e-38 Peak_05                           EtAc
Peak_16 1.201544e-11 Peak_16                        acetoin
Peak_20 4.089831e-04 Peak_20                      1-hexanol
Peak_23 8.486189e-34 Peak_23 2-ethylhexyl ester acetic acid
Peak_27 4.909888e-03 Peak_27                     1-heptanol
Peak_32 1.608030e-15 Peak_32                2-furanmethanol
Peak_33 5.764227e-17 Peak_33                      1-nonanol
##################################################################################################

ggplot(sigtab, aes(y=Compound, x=log2FoldChange)) + 
  geom_vline(xintercept = 0.0, color = "gray", size = 0.5) +
  geom_point(size=6) + 
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  ggtitle("Compounds signficantly differentiating Aa samples in 1.5 vs 15% nectar")+
  theme_bw()




#############################################################################################
###
##
#
# stopped here. will revist these followimg plots after auth 
################## 
# Non-PCoA Plots #
##################
###
##
# look at compound abundance over time by group

# melt and plot
VOC_melt <-psmelt(VOC)

# each compound over time
ggplot(VOC_melt, aes(x=day, y=Abundance, color=microbe))+
  geom_point()+
  geom_smooth()+
 facet_wrap(~Name, scales = "free")
###
##
# Compound abundance mean over days 1-2 by group

sample_data(NoZero)$TreatNect <- paste(sample_data(NoZero)$microbe, 
	sample_data(NoZero)$rep)

VOC_avg <- merge_samples(NoZero, group = "TreatNect", fun=mean)

otu_melt <-  psmelt((VOC_avg))
#
  
ggplot(otu_melt, aes(x= microbe, y= Abundance, group = microbe))+
  geom_point()+
  geom_boxplot()+
  facet_wrap(~Name, scales= "free")


###
##
# Histogram of compound abundance 

# 10 most abundant
VOC_avg_top <- prune_taxa(taxa_sums(VOC_avg)>7500000,VOC_avg)
avgtop_melt <-  psmelt((VOC_avg_top))
ggplot(avgtop_melt, aes(x=microbe, y=Abundance, fill=Name))+
	geom_bar(stat = "identity")+
	theme_bw() 

# 10 least abundant
VOC_avg_rare <- prune_taxa(taxa_sums(VOC_avg)<700000,VOC_avg)
avg_rare_melt <-  psmelt((VOC_avg_rare))
ggplot(avg_rare_melt, aes(x=microbe, y=Abundance, fill=Name))+
	geom_bar(stat = "identity")+
	theme_bw() 


###
##
#
#
##
###

##########
#  NMDS  #
##########

ord <- ordinate(VOC, method = "NMDS", distance = "bray")

ord
###########################################################################
Call:
metaMDS(comm = veganifyOTU(physeq), distance = distance) 

global Multidimensional Scaling using monoMDS

Data:     wisconsin(sqrt(veganifyOTU(physeq))) 
Distance: bray 

Dimensions: 2 
Stress:     0.1452752 
Stress type 1, weak ties
Two convergent solutions found after 20 tries
Scaling: centring, PC rotation, halfchange scaling 
Species: expanded scores based on 'wisconsin(sqrt(veganifyOTU(physeq)))' 
###########################################################################


plot_ordination(VOC, ord, color = "day", shape = "microbe", type = "samples")

plot_ordination(VOC, ord, color = "day", shape = "microbe", type = "samples")+
  theme_bw()+
  stat_ellipse(type="t")

plot_ordination(VOC, ord, color = "day", shape = "microbe", type = "samples")+
  stat_ellipse(type="t")


```