NAME RteMethParms
  RTEINTPARMS 0, 5, 1, 1, 0.2, 0, 5, 100, 0, 0, 1, 0
  RETURN

NAME LoadMiscParams
  LOCAL a$,b$,c$,d$
  a$="C:\Database\WILEY275.L"
  b$="C:\Database\PMR1124.L"
  c$="C:\Database\NIST14.L"
  d$=""
  QUALRPTOPT 0,1,0,0,"",1
  QUALPARMS a$,b$,c$,0.000000,0.000000,1,0.000000,0,d$
  PCTRPTOPT 0,0,1,0,"",0,0,""
  SPECTRAL_WINDOW = 0.200100
  PCTSCWIN = 0.020000
  MZRANGE = -0.300000:0.300000
  RteMethParms
  RETURN
