---
title: "SWD Behaviroial Response to Microbes when inoculated into Bluberry Juice"
author: "Brown, JT"
date: "August 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyr")
#install.packages("Rmisc")
library(Rmisc)
library(tidyr)
library(readxl)
library(ggplot2)
library(boot)
data = read_excel("~/GitHub/BACandBlue/data/bioassay/RAW_swd_vs_inoculated_blueberryjuice.xlsx", 
    sheet = "data4r")
#View(data)
```

```{r}
#################################################################################
###Subsetting data to look at the relationship between isolate and SWD behaviors
#################################################################################
data0621=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0621") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control) 

data0620=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0620") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control)

data0633=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0633") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control) 

data0185=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0185") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control) 

data0189=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0189") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control) 

data0634=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  dplyr::filter(microbe== "C0634") %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control) 


###########################################
#### Visualizing all the treatment results
###########################################
ggplot(data, aes(x=microbe, y=flies_in_treat))+geom_boxplot()+labs(x = "Microbe ID", y="# of Flies")

data1=data %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control) %>% 
  tidyr::gather(location, observed, flies_in_treat:flies_in_control)
ggplot(data1, aes(x=location, y=observed))+geom_boxplot()+facet_wrap(~microbe)+labs(x = "Treatment", y="# of Flies")+scale_x_discrete(labels=c("flies_in_treat"="Treatment", "flies_in_control"="Control", "flies_outside"="No Choice"))


##########################################################################################
#Normality Test and Linear models for the effect of each microbe on the flies in treatment
##########################################################################################
mod=lm(flies_in_treat~microbe,data)
summary(mod)
plot(mod)
mod0621=lm(observed~location,data0621)
summary(mod0621)
plot(mod0621)
mod0620=lm(observed~location,data0620)
summary(mod0620)
plot(mod0620)
mod0633=lm(observed~location,data0633)
summary(mod0633)
plot(mod0633)
mod0185=lm(observed~location,data0185)
summary(mod0185)
plot(mod0185)
mod0189=lm(observed~location,data0189)
summary(mod0189)
plot(mod0189)
mod0634=lm(observed~location,data0634)
summary(mod0634)
plot(mod0634)
```

```{r}
##########################################
#Index Plots with 95% confidence itervals
##########################################
data1=data %>% 
  mutate(data1,escaped=total_flies-(flies_in_treat+flies_in_control+flies_outside)) %>% 
  dplyr::select(microbe, flies_in_treat, flies_outside, flies_in_control, escaped) %>% 
  tidyr::gather(location, observed, flies_in_treat:escaped)
  

# calculate CI
data1=cbind(data1,CI=(CI(data1$observed,ci=0.95))) #CI(x=vector in question, ci=interval to be calculated)

# This creates the plot
ggplot(data=data1,aes(x=location,y=observed),group=microbe) + 
  ggtitle("Preference Index")+
  theme_classic()+
  facet_wrap(~microbe)+
  #theme(plot.title = element_text(hjust = 0.4),text = element_text(size=20), axis.text.y = element_text(angle=90, hjust=1,color="black"), axis.text.x = element_text(angle=0, hjust=1,color="black"))+ 
  geom_boxplot(fill="grey") + 
  labs(y="Index",y="Observed")+
  ylim(-1.0,1.0)+
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", colour = "Red",width=.1, show.legend=TRUE)+
  stat_summary(fun.y = mean, geom = "point", colour = "Red", show.legend=TRUE)+
  coord_flip() #Flips the graph on the side
  #geom_point(data=Infect_means,aes(x=Infect_means[,], colour = "Mean"),shape=21, size=2) +
  #geom_linerange(data=Infect_mean_ci,aes(xmin=mean-ci,xmax=mean+ci,x=mean,color="95% CI")) +
  #scale_color_manual(name = "", values = c("red", "red")) +
  #guides(shape=guide_legend(label.position = "topleft",override.aes = list()))+
  #guides(shape = guide_legend(override.aes = list(size = 5))) +
  #scale_color_manual(labels = c(values = c('lightskyblue1', 'lightpink'),'95% CI', 'Mean')) +
  #Adds boxplot elements
    #Adds title using the variable title
  #Centers the title; Adjust the hjust to modify the location
  #geom_errorbarh(aes(xmin = lower, xmax = upper), width=0.2)
  #coord_flip()+ #Flips the graph on the side
  #annotate("text",x=1.35,y=-0.5,label="Mean")+
  #annotate("text",x=1.3,y=-0.5,label="Median")+
  #annotate("text",x=1.25,y=-0.5,label="95% CI")+
  #annotate("pointrange",x=1.35,y=-0.65,ymin = 0.1, ymax = 0.1, colour = "red", size = 0.1)+
  #annotate("pointrange",x=1.3,y=-0.65,y=-0.65,ymin = -0.4, ymax = -0.6,
  #         colour = "black", size = 0.4,width=0.05)+
  #annotate("rect", xmin = 1.3, xmax = 1.3, ymin = -0.6, ymax =-0.7,
   #        alpha = .2, colour="black",size=0.8)+
  #annotate("errorbar",x=1.25,y=-0.65,ymin = -0.63, ymax = -0.67,
    #       colour = "red", size = 0.4,width=0.05)

rm(list=ls())

```
